services:
  - type: web
    name: thalf-chocolates
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_ji7cyTzN8rxp@ep-purple-fog-ax1182z2-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: NEXT_PUBLIC_WHATSAPP_NUMBER
        value: "919061107915"
      - key: NEXT_PUBLIC_RAZORPAY_KEY_ID
        value: rzp_test_TPaDCP7nB7ov9f
      - key: RAZORPAY_KEY_SECRET
        value: WJzKZvCZJhGz6Eqr5D5bSrbW
      - key: NEXT_PUBLIC_VAPID_PUBLIC_KEY
        value: BJNIIpHWfJb6Qpnwj6mA2QUG8xnza6SRWcoeVCNxO6kr5Bp1wthUjM1xv4fygOeUVdAzIeptroXg03c5vZg0bPQ
      - key: VAPID_PUBLIC_KEY
        value: BJNIIpHWfJb6Qpnwj6mA2QUG8xnza6SRWcoeVCNxO6kr5Bp1wthUjM1xv4fygOeUVdAzIeptroXg03c5vZg0bPQ
      - key: VAPID_PRIVATE_KEY
        value: vbb8mFYHtSxA0UwQaDq7tw0jtXGOGDz4j354mUhjCEM
      - key: VAPID_SUBJECT
        value: mailto:admin@thalf.com
